### ISSUE TITLE
Consider adding explicit sizes to <svg>

### ISSUE THREAD

**Issue by pepelsbey** [argyleink/Google-IO-2021-Workshop_User-Adaptive-Interfaces#6]
Currently icons are styled with external styles:

```html
<!-- index.html -->
<svg viewBox="0 0 24 24">
  <title>A note icon</title>
  <path d="M12 3v10.55c-.59-.34-1.27-.55-2-.55-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4V7h4V3h-6z"/>
</svg>
```
```css
/* index.css */
.fieldset-item svg {
  fill: var(--text2);
  block-size: var(--space-md);
}
```

<img width="1280" alt="Screenshot 2021-06-05 at 01 17 49" src="https://user-images.githubusercontent.com/105274/120869832-f96bde00-c59f-11eb-86d5-51b593f81985.png">

Unfortunately in some situations browsers give up on styles and fallback to HTML, it happens to me from time to time on cellular networks. Also Firefox has a tendency to flash unstyled markup just for a fraction of a second. And those huge black icons look so much worse than this:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/120869953-510a4980-c5a0-11eb-8a43-da440fe14efb.png">

You just need a couple of attributes. 16px * 2rem equals 32px, I guess:

```html
<svg viewBox="0 0 24 24" width="32" height="32">
  <title>A note icon</title>
  <path d="M12 3v10.55c-.59-.34-1.27-.55-2-.55-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4V7h4V3h-6z"/>
</svg>
```

**Comment by pepelsbey** [comment]
Side note: “Report a mistake” link at the bottom left corner of the [codelab](https://codelabs.developers.google.com/codelabs/user-adaptive-interfaces/) is broken:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/105274/120870433-99763700-c5a1-11eb-8ab7-9c1a1a2309e7.png">

It goes to https://github.com/googlecodelabs/user-adaptive-interfaces/issues, which doesn’t exist yet (or private).

**Comment by argyleink** [comment]
i've pinged someone internally who can help fix the report a mistake buttons in the codelabs 👍🏻 

unfortunately, if svg has inline height and widths then CSS sizes have no effect, and in this case I wanted design consistency via sizing the icon with a custom property and with logical properties. 

i agree tho, the flash of unstyled svg icons causes some massive layout shift. getting the stylesheet synchronously via the <head> tag should generally prevent that, development not so much, especially since vite has the body adopt stylesheets at runtime (so it can hot swap).

**Comment by pepelsbey** [comment]
> unfortunately, if svg has inline height and widths then CSS sizes have no effect

@argyleink but it **does** have effect https://codepen.io/pepelsbey/pen/QWpBvmo

That’s the whole point. It’s like adding width/height to `<img>` and then making it adaptive.

**Comment by argyleink** [comment]
hm, i tested in the form.. and it looks like i had a specificity issue.

**Comment by pepelsbey** [comment]
> it looks like i had a specificity issue

Oh, that famous one :D
